services:
  task-backend:
    build: ./backend
    container_name: task-backend
    ports:
      - '${PORT}:3000'
    env_file:
      - ./backend/.env
    restart: always

  task-frontend:
    build: ./
    container_name: task-frontend
    ports:
      - '4200:4200'
    restart: always

