services:
  task-backend:
    build: ./backend
    container_name: task-backend-staging
    ports:
      - "${PORT}:3001"
    environment:
      - PORT=${PORT}
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - MONGODB_USER=${MONGODB_USER}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - MONGODB_DBNAME=${MONGODB_DBNAME}
    restart: always

  task-frontend:
    build: ./
    container_name: task-frontend-staging
    ports:
      - "4201:4201"
    restart: always
