services:
  task-backend:
    build: ./backend
    container_name: task-backend-staging
    ports:
      - "${PORT}:3001"
    env_file:
      - ./backend/.env
    restart: always

  task-frontend:
    build: ./
    container_name: task-frontend-staging
    ports:
      - "4201:4200"
    restart: always
