name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Create backend .env file from GitHub secrets
        run: |
          mkdir -p backend
          cat <<EOF > backend/.env
          PORT=${{ secrets.PORT }}
          MONGO_URI=${{ secrets.MONGO_URI }}
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          EMAIL_USER=${{ secrets.EMAIL_USER }}
          EMAIL_PASS=${{ secrets.EMAIL_PASS }}
          MONGODB_USER=${{ secrets.MONGODB_USER }}
          MONGODB_PASSWORD=${{ secrets.MONGODB_PASSWORD }}
          MONGODB_DBNAME=${{ secrets.MONGODB_DBNAME }}
          EOF

      - name: Build and run containers
        run: docker compose up -d --build

      - name: Wait for services to stabilize
        run: sleep 15

      - name: Health check - Backend
        run: curl --fail http://localhost:3000 || exit 1

      - name: Health check - Frontend
        run: curl --fail http://localhost:4200 || exit 1

      - name: Shut down containers
        run: docker compose down
